#turtlebot3_my_model:
# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers -> check urdf file hardwareinterface
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint1_left_joint
  pid: {p: 2.5, i: 0.0, d: 0.01}

joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint1_right_joint
  pid: {p: 2.5, i: 0.0, d: 0.01}

joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint2_left_joint
  pid: {p: 3.0, i: 0.0, d: 0.00}

joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint2_right_joint
  pid: {p: 3.0, i: 0.0, d: 0.00}

