# gazebo_ros_control_params.yaml
gazebo_ros_control/pid_gains:
  joint1_left_joint: {p: 10.0, i: 0.0, d: 0.1}
  joint1_right_joint: {p: 10.0, i: 0.0, d: 0.1}
  joint2_left_joint: {p: 5.0, i: 0.0, d: 0.0}
  joint2_right_joint: {p: 5.0, i: 0.0, d: 0.0}